package org.flysnow.cloud.buildmeta.domain.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.flysnow.cloud.buildmeta.domain.model.Branch;
import org.flysnow.cloud.buildmeta.domain.model.BranchExample;

public interface BranchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table branch
     *
     * @mbggenerated Tue Sep 09 14:17:36 CST 2014
     */
    int countByExample(BranchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table branch
     *
     * @mbggenerated Tue Sep 09 14:17:36 CST 2014
     */
    int deleteByExample(BranchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table branch
     *
     * @mbggenerated Tue Sep 09 14:17:36 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table branch
     *
     * @mbggenerated Tue Sep 09 14:17:36 CST 2014
     */
    int insert(Branch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table branch
     *
     * @mbggenerated Tue Sep 09 14:17:36 CST 2014
     */
    int insertSelective(Branch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table branch
     *
     * @mbggenerated Tue Sep 09 14:17:36 CST 2014
     */
    List<Branch> selectByExample(BranchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table branch
     *
     * @mbggenerated Tue Sep 09 14:17:36 CST 2014
     */
    Branch selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table branch
     *
     * @mbggenerated Tue Sep 09 14:17:36 CST 2014
     */
    int updateByExampleSelective(@Param("record") Branch record, @Param("example") BranchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table branch
     *
     * @mbggenerated Tue Sep 09 14:17:36 CST 2014
     */
    int updateByExample(@Param("record") Branch record, @Param("example") BranchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table branch
     *
     * @mbggenerated Tue Sep 09 14:17:36 CST 2014
     */
    int updateByPrimaryKeySelective(Branch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table branch
     *
     * @mbggenerated Tue Sep 09 14:17:36 CST 2014
     */
    int updateByPrimaryKey(Branch record);
}