package org.flysnow.cloud.buildmeta.domain.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.flysnow.cloud.buildmeta.domain.model.Build;
import org.flysnow.cloud.buildmeta.domain.model.BuildExample;

public interface BuildMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table build
     *
     * @mbggenerated Tue Sep 09 14:17:36 CST 2014
     */
    int countByExample(BuildExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table build
     *
     * @mbggenerated Tue Sep 09 14:17:36 CST 2014
     */
    int deleteByExample(BuildExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table build
     *
     * @mbggenerated Tue Sep 09 14:17:36 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table build
     *
     * @mbggenerated Tue Sep 09 14:17:36 CST 2014
     */
    int insert(Build record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table build
     *
     * @mbggenerated Tue Sep 09 14:17:36 CST 2014
     */
    int insertSelective(Build record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table build
     *
     * @mbggenerated Tue Sep 09 14:17:36 CST 2014
     */
    List<Build> selectByExample(BuildExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table build
     *
     * @mbggenerated Tue Sep 09 14:17:36 CST 2014
     */
    Build selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table build
     *
     * @mbggenerated Tue Sep 09 14:17:36 CST 2014
     */
    int updateByExampleSelective(@Param("record") Build record, @Param("example") BuildExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table build
     *
     * @mbggenerated Tue Sep 09 14:17:36 CST 2014
     */
    int updateByExample(@Param("record") Build record, @Param("example") BuildExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table build
     *
     * @mbggenerated Tue Sep 09 14:17:36 CST 2014
     */
    int updateByPrimaryKeySelective(Build record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table build
     *
     * @mbggenerated Tue Sep 09 14:17:36 CST 2014
     */
    int updateByPrimaryKey(Build record);
}