package org.flysnow.cloud.buildmeta.domain.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.flysnow.cloud.buildmeta.domain.model.Collector;
import org.flysnow.cloud.buildmeta.domain.model.CollectorExample;

public interface CollectorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collector
     *
     * @mbggenerated Wed Oct 22 14:48:18 CST 2014
     */
    int countByExample(CollectorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collector
     *
     * @mbggenerated Wed Oct 22 14:48:18 CST 2014
     */
    int deleteByExample(CollectorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collector
     *
     * @mbggenerated Wed Oct 22 14:48:18 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collector
     *
     * @mbggenerated Wed Oct 22 14:48:18 CST 2014
     */
    int insert(Collector record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collector
     *
     * @mbggenerated Wed Oct 22 14:48:18 CST 2014
     */
    int insertSelective(Collector record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collector
     *
     * @mbggenerated Wed Oct 22 14:48:18 CST 2014
     */
    List<Collector> selectByExampleWithBLOBs(CollectorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collector
     *
     * @mbggenerated Wed Oct 22 14:48:18 CST 2014
     */
    List<Collector> selectByExample(CollectorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collector
     *
     * @mbggenerated Wed Oct 22 14:48:18 CST 2014
     */
    Collector selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collector
     *
     * @mbggenerated Wed Oct 22 14:48:18 CST 2014
     */
    int updateByExampleSelective(@Param("record") Collector record, @Param("example") CollectorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collector
     *
     * @mbggenerated Wed Oct 22 14:48:18 CST 2014
     */
    int updateByExampleWithBLOBs(@Param("record") Collector record, @Param("example") CollectorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collector
     *
     * @mbggenerated Wed Oct 22 14:48:18 CST 2014
     */
    int updateByExample(@Param("record") Collector record, @Param("example") CollectorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collector
     *
     * @mbggenerated Wed Oct 22 14:48:18 CST 2014
     */
    int updateByPrimaryKeySelective(Collector record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collector
     *
     * @mbggenerated Wed Oct 22 14:48:18 CST 2014
     */
    int updateByPrimaryKeyWithBLOBs(Collector record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collector
     *
     * @mbggenerated Wed Oct 22 14:48:18 CST 2014
     */
    int updateByPrimaryKey(Collector record);
}