package org.flysnow.cloud.buildmeta.domain.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.flysnow.cloud.buildmeta.domain.model.Farm;
import org.flysnow.cloud.buildmeta.domain.model.FarmExample;

public interface FarmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farm
     *
     * @mbggenerated Mon Oct 27 10:29:23 CST 2014
     */
    int countByExample(FarmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farm
     *
     * @mbggenerated Mon Oct 27 10:29:23 CST 2014
     */
    int deleteByExample(FarmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farm
     *
     * @mbggenerated Mon Oct 27 10:29:23 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farm
     *
     * @mbggenerated Mon Oct 27 10:29:23 CST 2014
     */
    int insert(Farm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farm
     *
     * @mbggenerated Mon Oct 27 10:29:23 CST 2014
     */
    int insertSelective(Farm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farm
     *
     * @mbggenerated Mon Oct 27 10:29:23 CST 2014
     */
    List<Farm> selectByExample(FarmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farm
     *
     * @mbggenerated Mon Oct 27 10:29:23 CST 2014
     */
    Farm selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farm
     *
     * @mbggenerated Mon Oct 27 10:29:23 CST 2014
     */
    int updateByExampleSelective(@Param("record") Farm record, @Param("example") FarmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farm
     *
     * @mbggenerated Mon Oct 27 10:29:23 CST 2014
     */
    int updateByExample(@Param("record") Farm record, @Param("example") FarmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farm
     *
     * @mbggenerated Mon Oct 27 10:29:23 CST 2014
     */
    int updateByPrimaryKeySelective(Farm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farm
     *
     * @mbggenerated Mon Oct 27 10:29:23 CST 2014
     */
    int updateByPrimaryKey(Farm record);
}