package org.flysnow.cloud.buildmeta.domain.model;

public class Build {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column build.id
     *
     * @mbggenerated Tue Sep 09 14:17:36 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column build.repo_url
     *
     * @mbggenerated Tue Sep 09 14:17:36 CST 2014
     */
    private String repoUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column build.branch
     *
     * @mbggenerated Tue Sep 09 14:17:36 CST 2014
     */
    private String branch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column build.group_id
     *
     * @mbggenerated Tue Sep 09 14:17:36 CST 2014
     */
    private String groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column build.artifact_id
     *
     * @mbggenerated Tue Sep 09 14:17:36 CST 2014
     */
    private String artifactId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column build.packaging
     *
     * @mbggenerated Tue Sep 09 14:17:36 CST 2014
     */
    private String packaging;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column build.type
     *
     * @mbggenerated Tue Sep 09 14:17:36 CST 2014
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column build.version
     *
     * @mbggenerated Tue Sep 09 14:17:36 CST 2014
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column build.md5
     *
     * @mbggenerated Tue Sep 09 14:17:36 CST 2014
     */
    private String md5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column build.download_url
     *
     * @mbggenerated Tue Sep 09 14:17:36 CST 2014
     */
    private String downloadUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column build.classifier
     *
     * @mbggenerated Tue Sep 09 14:17:36 CST 2014
     */
    private String classifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column build.created
     *
     * @mbggenerated Tue Sep 09 14:17:36 CST 2014
     */
    private Long created;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column build.id
     *
     * @return the value of build.id
     *
     * @mbggenerated Tue Sep 09 14:17:36 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column build.id
     *
     * @param id the value for build.id
     *
     * @mbggenerated Tue Sep 09 14:17:36 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column build.repo_url
     *
     * @return the value of build.repo_url
     *
     * @mbggenerated Tue Sep 09 14:17:36 CST 2014
     */
    public String getRepoUrl() {
        return repoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column build.repo_url
     *
     * @param repoUrl the value for build.repo_url
     *
     * @mbggenerated Tue Sep 09 14:17:36 CST 2014
     */
    public void setRepoUrl(String repoUrl) {
        this.repoUrl = repoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column build.branch
     *
     * @return the value of build.branch
     *
     * @mbggenerated Tue Sep 09 14:17:36 CST 2014
     */
    public String getBranch() {
        return branch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column build.branch
     *
     * @param branch the value for build.branch
     *
     * @mbggenerated Tue Sep 09 14:17:36 CST 2014
     */
    public void setBranch(String branch) {
        this.branch = branch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column build.group_id
     *
     * @return the value of build.group_id
     *
     * @mbggenerated Tue Sep 09 14:17:36 CST 2014
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column build.group_id
     *
     * @param groupId the value for build.group_id
     *
     * @mbggenerated Tue Sep 09 14:17:36 CST 2014
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column build.artifact_id
     *
     * @return the value of build.artifact_id
     *
     * @mbggenerated Tue Sep 09 14:17:36 CST 2014
     */
    public String getArtifactId() {
        return artifactId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column build.artifact_id
     *
     * @param artifactId the value for build.artifact_id
     *
     * @mbggenerated Tue Sep 09 14:17:36 CST 2014
     */
    public void setArtifactId(String artifactId) {
        this.artifactId = artifactId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column build.packaging
     *
     * @return the value of build.packaging
     *
     * @mbggenerated Tue Sep 09 14:17:36 CST 2014
     */
    public String getPackaging() {
        return packaging;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column build.packaging
     *
     * @param packaging the value for build.packaging
     *
     * @mbggenerated Tue Sep 09 14:17:36 CST 2014
     */
    public void setPackaging(String packaging) {
        this.packaging = packaging;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column build.type
     *
     * @return the value of build.type
     *
     * @mbggenerated Tue Sep 09 14:17:36 CST 2014
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column build.type
     *
     * @param type the value for build.type
     *
     * @mbggenerated Tue Sep 09 14:17:36 CST 2014
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column build.version
     *
     * @return the value of build.version
     *
     * @mbggenerated Tue Sep 09 14:17:36 CST 2014
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column build.version
     *
     * @param version the value for build.version
     *
     * @mbggenerated Tue Sep 09 14:17:36 CST 2014
     */
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column build.md5
     *
     * @return the value of build.md5
     *
     * @mbggenerated Tue Sep 09 14:17:36 CST 2014
     */
    public String getMd5() {
        return md5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column build.md5
     *
     * @param md5 the value for build.md5
     *
     * @mbggenerated Tue Sep 09 14:17:36 CST 2014
     */
    public void setMd5(String md5) {
        this.md5 = md5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column build.download_url
     *
     * @return the value of build.download_url
     *
     * @mbggenerated Tue Sep 09 14:17:36 CST 2014
     */
    public String getDownloadUrl() {
        return downloadUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column build.download_url
     *
     * @param downloadUrl the value for build.download_url
     *
     * @mbggenerated Tue Sep 09 14:17:36 CST 2014
     */
    public void setDownloadUrl(String downloadUrl) {
        this.downloadUrl = downloadUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column build.classifier
     *
     * @return the value of build.classifier
     *
     * @mbggenerated Tue Sep 09 14:17:36 CST 2014
     */
    public String getClassifier() {
        return classifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column build.classifier
     *
     * @param classifier the value for build.classifier
     *
     * @mbggenerated Tue Sep 09 14:17:36 CST 2014
     */
    public void setClassifier(String classifier) {
        this.classifier = classifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column build.created
     *
     * @return the value of build.created
     *
     * @mbggenerated Tue Sep 09 14:17:36 CST 2014
     */
    public Long getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column build.created
     *
     * @param created the value for build.created
     *
     * @mbggenerated Tue Sep 09 14:17:36 CST 2014
     */
    public void setCreated(Long created) {
        this.created = created;
    }
}