package org.flysnow.cloud.buildmeta.domain.model;

public class Collector {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collector.id
     *
     * @mbggenerated Mon Nov 17 14:28:53 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collector.scalr_url
     *
     * @mbggenerated Mon Nov 17 14:28:53 CST 2014
     */
    private String scalrUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collector.env_id
     *
     * @mbggenerated Mon Nov 17 14:28:53 CST 2014
     */
    private String envId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collector.role
     *
     * @mbggenerated Mon Nov 17 14:28:53 CST 2014
     */
    private String role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collector.target
     *
     * @mbggenerated Mon Nov 17 14:28:53 CST 2014
     */
    private String target;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collector.c_type
     *
     * @mbggenerated Mon Nov 17 14:28:53 CST 2014
     */
    private String cType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collector.id
     *
     * @return the value of collector.id
     *
     * @mbggenerated Mon Nov 17 14:28:53 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collector.id
     *
     * @param id the value for collector.id
     *
     * @mbggenerated Mon Nov 17 14:28:53 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collector.scalr_url
     *
     * @return the value of collector.scalr_url
     *
     * @mbggenerated Mon Nov 17 14:28:53 CST 2014
     */
    public String getScalrUrl() {
        return scalrUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collector.scalr_url
     *
     * @param scalrUrl the value for collector.scalr_url
     *
     * @mbggenerated Mon Nov 17 14:28:53 CST 2014
     */
    public void setScalrUrl(String scalrUrl) {
        this.scalrUrl = scalrUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collector.env_id
     *
     * @return the value of collector.env_id
     *
     * @mbggenerated Mon Nov 17 14:28:53 CST 2014
     */
    public String getEnvId() {
        return envId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collector.env_id
     *
     * @param envId the value for collector.env_id
     *
     * @mbggenerated Mon Nov 17 14:28:53 CST 2014
     */
    public void setEnvId(String envId) {
        this.envId = envId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collector.role
     *
     * @return the value of collector.role
     *
     * @mbggenerated Mon Nov 17 14:28:53 CST 2014
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collector.role
     *
     * @param role the value for collector.role
     *
     * @mbggenerated Mon Nov 17 14:28:53 CST 2014
     */
    public void setRole(String role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collector.target
     *
     * @return the value of collector.target
     *
     * @mbggenerated Mon Nov 17 14:28:53 CST 2014
     */
    public String getTarget() {
        return target;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collector.target
     *
     * @param target the value for collector.target
     *
     * @mbggenerated Mon Nov 17 14:28:53 CST 2014
     */
    public void setTarget(String target) {
        this.target = target;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collector.c_type
     *
     * @return the value of collector.c_type
     *
     * @mbggenerated Mon Nov 17 14:28:53 CST 2014
     */
    public String getcType() {
        return cType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collector.c_type
     *
     * @param cType the value for collector.c_type
     *
     * @mbggenerated Mon Nov 17 14:28:53 CST 2014
     */
    public void setcType(String cType) {
        this.cType = cType;
    }
}