package org.flysnow.cloud.buildmeta.domain.model;

public class Repository {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.id
     *
     * @mbggenerated Tue Sep 09 14:17:36 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.repo_url
     *
     * @mbggenerated Tue Sep 09 14:17:36 CST 2014
     */
    private String repoUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repository.id
     *
     * @return the value of repository.id
     *
     * @mbggenerated Tue Sep 09 14:17:36 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repository.id
     *
     * @param id the value for repository.id
     *
     * @mbggenerated Tue Sep 09 14:17:36 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repository.repo_url
     *
     * @return the value of repository.repo_url
     *
     * @mbggenerated Tue Sep 09 14:17:36 CST 2014
     */
    public String getRepoUrl() {
        return repoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repository.repo_url
     *
     * @param repoUrl the value for repository.repo_url
     *
     * @mbggenerated Tue Sep 09 14:17:36 CST 2014
     */
    public void setRepoUrl(String repoUrl) {
        this.repoUrl = repoUrl;
    }
}